@startuml
'https://plantuml.com/class-diagram

class Main{
+ static void main(String[] args)
}

class StartMenu {
+ loginAndSignUp()

}

class User {
- String selectedMovies
- String selectedSeries
- ArrayList<Movie> watchedMovies
- ArrayList<Series> watchedSeries
- LinkedList<String> saveList
- String userDataFile
+ createAccount()
+ getAccountInfo()
+ doesUserExist()
}

class FileIO {
+ loadMoviesFromList()
+ loadSeriesFromList()
}

interface Media {
resumePlay();
stopPlay();
pausePlay();

}

abstract MediaData{
- String name
- String genre
- int releaseYear
- float rating
+ String getName()
+ String getGenre()
+ int getReleaseYear()
+ float getRating()

}

class NetflixMenu {
- TreeSet<MediaList> searchMedia
- ArrayList<Genre> genreList
- ArrayList<Movie> movieList
- ArrayList<Series> seriesList
+ void initializeGenreList()
+ void displayMovieList()
+ void displaySeriesList()
+ void displaySeriesList()
+ void displayGenreList()
+ void displaySearchMedia(TreeSet<MediaData> searchMedia)
+ void searchMedia(String keyword)
+ ArrayList<String> getMoviesList()
+ ArrayList<String> getSeriesList()
}

class Movie {
+ String toString()
+ int compareTo(MediaData o)
}

class Genre {
- ArrayList<String> genre
+ ArrayList<String> getGenre()
+ String mediaWithThisGenre()
+ mediaWithThisGenre()
}

class Series {
- ArrayList<String> seasonEpisode
+ ArrayList<String> getSeasonEpisode()
+ String toString()
+ int compareTo(MediaData o)
}

class Season {
}

class Episode {
}

class TextUI {
- Scanner scanner
+ void displayMsg()
+ void displayMovie(String movieName)
+ void displaySeries(String seriesName, String season, String episode)
}

Main -- StartMenu
StartMenu *-- User
TextUI *- StartMenu
User *- NetflixMenu
NetflixMenu -- Movie
NetflixMenu -- Series
NetflixMenu -- Genre
Genre --> Movie
Genre --> Series
Series *-- Season
Season *-- Episode
Media *-- Movie
Media *-- Series
FileIO *-- User
MediaData *-- Movie
MediaData *-- Series
FileIO *-- MediaData

@enduml