@startuml
'https://plantuml.com/class-diagram

class Main{
+ static void main(String[] args)
}

class StartMenu {
+ logIn()
+ signUp()
}

class User {
- ArrayList<Movie> watchedMovies
- ArrayList<Series> watchedSeries
- LinkedList<String> watchLater
+ createAccount()
+ getAccountInfo()
}

class FileIO {
+ ArrayList<String> ReadFileData(String path)
+ void readUserData(ArrayList<Users> user, String path)
+ void saveUserData(ArrayList<Users> user, String path)
}

interface Media {
resumePlay();
stopPlay();
pausePlay();

}
abstract MediaData{
- String name()
- String genre()
- int ReleaseYear()
- int Rating()


}

class NetflixMenu {
- TreeSet<MediaList> searchMedia
- ArrayList<Genre> genreList
- ArrayList<Movie> movieList
- ArrayList<Series> seriesList
- ArrayList<User> userList

}

class Movie {
}

class Genre {
- ArrayList<String> genre
+ mediaWithThisGenre()
}

class Series {
- ArrayList<String> season
}

class Season {
- ArrayList<String> episode
}

class Episode {

}

class TextUI {
- Scanner scanner
+ void displayMsg()
+ void displayMovie(String movieName)
+ void displaySeries(String seriesName, String season, String episode)
}

Main *--- StartMenu
StartMenu *-- User
User <|-- NetflixMenu
NetflixMenu <|-- Movie
NetflixMenu <|-- Series
NetflixMenu <|-- Genre
Genre --> Movie
Genre --> Series
Series *-- Season
Season *-- Episode
Media *-- Movie
Media *-- Series
FileIO *-- User
TextUI *-- User
TextUI *-- StartMenu
MediaData *-- Movie
MediaData *-- Series
FileIO *-- MediaData

@enduml